import { Header } from "@/layouts/header";
import { Providers } from "@/lib/wagmi/provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-US">
      <body className={`${poppins.variable} `}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
